---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: {{ .Values.geth.diskSizeGB }}Gi
