---
apiVersion: v2
name: common
version: 0.2.7
type: library
home: https://celo.org
icon: >
  https://github.com/celo-org/charts/blob/main/static/celo_logo256x256.png?raw=true
description: Helm chart with helper templates and functions for Celo nodes.
  Import into your chart with `dependencies` and use the templates and functions
keywords:
  - celo
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
