---
image:
  tag: dev-jcortejoso
init:
  contracts:
    enabled: true
    urls:
      deployment-l1.json: https://storage.googleapis.com/cel2-rollup-files/baklava/deployment-l1.json
      rollup.json: https://storage.googleapis.com/cel2-rollup-files/baklava/rollup.json
      genesis.json: https://storage.googleapis.com/cel2-rollup-files/baklava/genesis.json
      prestate.bin.gz: https://storage.googleapis.com/cel2-rollup-files/baklava/prestate.bin.gz
secrets:
  # Private Key for the proposer. Either provide the secret name and key or the value directly. If value is not empty, it will have precedence over the secret.
  privateKey:
    value: 0xa59dba48fba0901c00164473d11038190fda2005a1c2d83bcf76aff145343af3
  # L1 URL for the proposer. Either provide the secret name and key or the value directly. If value is not empty, it will have precedence over the secret.
  l1Url:
    value: https://ethereum-holesky-rpc.publicnode.com
