# Default values for eksportisto-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  # -- Image repository trigger
  repository: grafana/agent
  # -- Image pull policy
  imagePullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Service parameters.
service:
  port: 80

# -- Cluster where Eksportisto is deployed, added as an external Prometheus label.
cluster: mainnet

remote_write:
  # -- Prometheus remote_write destination.
  url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  # -- Prometheus remote_write credentials, stored in Akeyless.
  basic_auth:
    username: EKSPORTISTO_PROMETHEUS_USERNAME
    password: EKSPORTISTO_PROMETHEUS_PASSWORD
