---
apiVersion: v2
appVersion: "1.0"
description: Chart wrapper over celo-fullnode chart to adapt to Forno.
  It requires a Kong controller, kong ingressClass and kong crds installed in the cluster.
name: kong-celo-fullnode
version: 0.5.2
icon: >
  https://github.com/celo-org/charts/blob/main/static/celo_logo256x256.png?raw=true
type: application
dependencies:
  - name: celo-fullnode
    repository: oci://us-west1-docker.pkg.dev/devopsre/clabs-public-oci
    version: "~0.4.0"
    alias: celo_fullnode
  - name: common
    repository: oci://us-west1-docker.pkg.dev/devopsre/clabs-public-oci
    version: "~0.2.0"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
