apiVersion: configuration.konghq.com/v1
config:
  fault_tolerant: true
  hide_client_headers: false
  {{- if .Values.rate_limit.hour }}
  hour: {{ .Values.rate_limit.hour }}
  {{- end }}
  {{- if .Values.rate_limit.minute }}
  minute: {{ .Values.rate_limit.minute }}
  {{- end }}
  {{- if .Values.rate_limit.second }}
  minute: {{ .Values.rate_limit.second }}
  {{- end }}
  policy: redis
  redis_host: redis-master
  redis_password: {{ .Values.redisPassword }}
  redis_ssl: false
  redis_ssl_verify: false
kind: KongPlugin
metadata:
  name: {{ $.Release.Name }}-rate-limit
  labels:
    app: {{ $.Release.Name }}
plugin: rate-limiting
