apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "rosetta.labels" . | nindent 4 }}
    component: server
  name: {{ include "rosetta.fullname" . }}
spec:
  ipFamilies:
  - IPv4
  ports:
  - name: http
    port: 8080
  selector:
    {{- include "rosetta.selectorLabels" . | nindent 4 }}
    component: server
