apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-bootnode.fullname" . }}
  labels:
    {{- include "op-bootnode.labels" . | nindent 4 }}
data:
  p2p.hex: {{ .Values.config.p2p.keys | b64enc | quote }}
