---
config: |
  [server]
  rpc_host = "0.0.0.0"
  rpc_port = {{ .Values.service.rpcPort | default 8080 }}
  ws_host = "0.0.0.0"
  ws_port = {{ .Values.service.wsPort | default 8085 }}
  max_body_size_bytes = 10485760
  max_concurrent_rpcs = 1000
  log_level = "debug"

  [metrics]
  enabled = {{ .Values.metrics.enabled }}
  host = "0.0.0.0"
  port = {{ .Values.metrics.port | default 9761 }}

  [backends]
  [backends.public]
  rpc_url = "https://ethereum-holesky-rpc.publicnode.com"
  ws_url = "wss://ethereum-holesky-rpc.publicnode.com"
  consensus_receipts_target = "eth_getBlockReceipts"

  [backend_groups]
  [backend_groups.main]
  backends = ["public"]

podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "9761"
  prometheus.io/scrape: "true"
