{{- if .Values.blockscout.metadataCrawler.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-metadata-crawler
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-metadata-crawler
spec:
  schedule: "{{ .Values.blockscout.metadataCrawler.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "celo.blockscout.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ .Release.Name }}-rbac
          initContainers:
          {{- include "celo.blockscout.initContainer.secrets-init" . | nindent 10 }}
          containers:
          {{- $data := dict "Values" .Values "Database" .Values.blockscout.indexer.db }}
          {{- include "celo.blockscout.container.db-terminating-sidecar" $data | nindent 10 }}
          - name: metadata-crawler
            image: {{ .Values.blockscout.metadataCrawler.image.repository }}:{{ .Values.blockscout.metadataCrawler.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /tmp/pod/secrets-init
            args:
            - --provider
            - google
            - /bin/sh
            - -c
            - |
              trap "touch /tmp/pod/main-terminated" EXIT
              node lib/crawler.js
            env:
            - name: LOG_FORMAT
              value: stackdriver
            - name: PGHOST
              value: "127.0.0.1"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "blockscout"
            - name: PROVIDER_URL
              value: {{ .Values.network.nodes.archiveNodes.jsonrpcHttpUrl }}
            - name: PGUSER
              value: {{ .Values.blockscout.shared.secrets.dbUser }}
            - name: PGPASSWORD
              value: {{ .Values.blockscout.shared.secrets.dbPassword }}
            {{- include "celo.blockscout.conditional-env-var" (dict "name" "DISCORD_WEBHOOK_URL" "value" .Values.blockscout.shared.secrets.discordWebhookUrl) | nindent 12 }}
            {{- include "celo.blockscout.conditional-env-var" (dict "name" "CLUSTER_NAME" "value" .Values.blockscout.metadataCrawler.discordClusterName) | nindent 12 }}
            volumeMounts:
            - mountPath: /tmp/pod
              name: temporary-dir
          volumes:
            {{- include "celo.blockscout.volume.cloudsql-credentials" . | nindent 12 }}
            {{- include "celo.blockscout.volume.temporary-dir" . | nindent 12 }}
          restartPolicy: Never
{{- end }}
