---
{{- $gcp_service_account_name := .Values.infrastructure.gcp.serviceAccount | default (printf "%s@%s.iam.gserviceaccount.com" .Release.Name .Values.infrastructure.gcp.projectId) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $gcp_service_account_name }}
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    helm.sh/resource-policy: keep
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    helm.sh/resource-policy: keep
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
