apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-indexer
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-indexer
  annotations:
    {{- include "celo.blockscout.annotations" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.blockscout.indexer.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.blockscout.indexer.strategy.rollingUpdate.maxUnavailable }}
  replicas: 1
  selector:
    matchLabels:
      app: blockscout
      release: {{ .Release.Name }}
      component: blockscout-indexer
  template:
    metadata:
      {{- if .Values.infrastructure.metrics.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "4001"
        prometheus.io/scrape: "true"
      {{- end}}
      labels:
        app: blockscout
        release: {{ .Release.Name }}
        component: blockscout-indexer
        {{- include "celo.blockscout.elixir.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: {{ .Values.blockscout.indexer.terminationGracePeriodSeconds }}
      initContainers:
      {{- include "celo.blockscout.initContainer.secrets-init" . | nindent 6 }}
      containers:
        {{- $data := dict "Release" .Release "Values" .Values "Database" .Values.blockscout.indexer.db -}}
        {{- include "celo.blockscout.container.db-sidecar" $data | nindent 6 }}
      - name: blockscout-indexer
        image: {{ .Values.blockscout.shared.image.repository }}:{{ .Values.blockscout.shared.image.tag }}
        imagePullPolicy: {{ .Values.blockscout.shared.image.pullPolicy }}
        command:
        - /secrets/secrets-init
        args:
        - --provider
        - google
        - /bin/sh
        - -c
        - |
           exec mix cmd --app indexer "iex --cookie $ERLANG_COOKIE --name {{ .Values.blockscout.shared.erlangNodeName}}@$(POD_IP) -e 'IEx.configure(default_prompt: \"\", alive_prompt: \"\")' -S mix run --no-compile"
        volumeMounts:
        - mountPath: /secrets
          name: temporary-dir
          readOnly: true
        ports:
        - name: health
          containerPort: {{ .Values.blockscout.indexer.port }}
        {{- with .Values.blockscout.indexer.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.blockscout.indexer.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.blockscout.indexer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: HEALTH_CHECK_PORT
          value: {{ .Values.blockscout.indexer.port | quote }}
        - name: DISABLE_WEBAPP
          value: "true"
        - name: POOL_SIZE
          value: {{ .Values.blockscout.indexer.poolSize | quote }}
        - name: POOL_SIZE_API
          value: {{ .Values.blockscout.indexer.poolSizeReplica | quote }}
        - name: METRICS_ENABLED
          value: {{ .Values.infrastructure.metrics.enabled | quote }}
        - name: INDEXER_DISABLE_EMPTY_BLOCK_SANITIZER
          value: "false"
        - name: DISPLAY_REWARDS
          value: {{.Values.blockscout.shared.epochRewards.enabled | quote}}
        - name: MY_REGION
          value: {{ .Values.blockscout.indexer.rpcRegion | quote }}
        - name: FLY_REGION
          value: {{ .Values.blockscout.indexer.rpcRegion | quote }}
        - name: PRIMARY_REGION
          value: {{ .Values.blockscout.indexer.primaryRpcRegion | quote }}
        - name: INDEXER_DISABLE_BLOCK_REWARD_FETCHER
          value: {{ not .Values.blockscout.indexer.fetchers.blockRewards.enabled | quote }}
        {{- include "celo.blockscout.env-vars" $data | nindent 8 }}
      volumes:
        {{- include "celo.blockscout.volume.cloudsql-credentials" . | nindent 8 }}
        {{- include "celo.blockscout.volume.temporary-dir" . | nindent 8 }}
      {{- $affinity := default .Values.infrastructure.affinity.affinity .Values.blockscout.indexer.affinity -}}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $nodeSelector := default .Values.infrastructure.affinity.nodeSelector .Values.blockscout.indexer.nodeSelector -}}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
