{{- if gt (int .Values.blockscout.eventStream.replicas) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-event-stream
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-event-stream
  annotations:
    {{- include "celo.blockscout.annotations" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.blockscout.eventStream.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.blockscout.eventStream.strategy.rollingUpdate.maxUnavailable }}
  replicas: {{ .Values.blockscout.eventStream.replicas }}
  selector:
    matchLabels:
      app: blockscout
      release: {{ .Release.Name }}
      component: blockscout-event-stream
  template:
    metadata:
      {{- if .Values.infrastructure.metrics.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port:  {{ .Values.blockscout.eventStream.port | quote }}
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app: blockscout
        release: {{ .Release.Name }}
        component: blockscout-event-stream
        {{- include "celo.blockscout.elixir.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: {{ .Values.blockscout.eventStream.terminationGracePeriodSeconds }}
      initContainers:
      {{- include "celo.blockscout.container.init-container-wait-sql-instance" . | nindent 6 }}
      {{- include "celo.blockscout.initContainer.secrets-init" . | nindent 6 }}
      containers:
      - name: blockscout-event-stream
        image: {{ .Values.blockscout.shared.image.repository }}:{{ .Values.blockscout.shared.image.tag }}
        imagePullPolicy: {{ .Values.blockscout.shared.image.pullPolicy }}
        command:
        - /secrets/secrets-init
        args:
        - --provider
        - google
        - /bin/sh
        - -c
        - |
           exec mix cmd --app event_stream "elixir --cookie $ERLANG_COOKIE --name {{ .Values.blockscout.shared.erlangNodeName}}@$(POD_IP) -S mix phx.server --no-compile" 
        volumeMounts:
        - mountPath: /secrets
          name: temporary-dir
          readOnly: true
        ports:
        - name: health
          containerPort: {{ .Values.blockscout.eventStream.port }}
        {{- with .Values.blockscout.eventStream.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.blockscout.eventStream.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.blockscout.eventStream.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: METRICS_ENABLED
          value: {{ .Values.infrastructure.metrics.enabled | quote }}
        - name: ENABLE_EVENT_STREAM
          value: {{ (ternary "true" "false" (gt (int .Values.blockscout.eventStream.replicas) 0)) | quote }}
        - name: BEANSTALKD_PORT
          value: {{ .Values.blockscout.eventStream.beanstalkdPort | quote }}
        - name: BEANSTALKD_HOST
          value: {{ .Values.blockscout.eventStream.beanstalkdHost | quote }}
        - name: ERLANG_COOKIE
          value: {{ .Values.blockscout.shared.secrets.erlang_cookie }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EPMD_SERVICE_NAME
          value: {{ .Release.Name }}-epmd-service
      volumes:
      {{- include "celo.blockscout.volume.temporary-dir" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
