---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-rbac
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
    "iam.gke.io/gcp-service-account": {{ .Release.Name }}-rbac@{{ .Values.infrastructure.gcp.projectId }}.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
rules:
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-rbac
  namespace: {{ .Release.Namespace }}
---
{{- $gcp_service_account_name_sql_created := include "celo.blockscout.sanitize-gcp-service-account-name" (dict "name" (printf "%s-cloudsql" .Release.Name)) -}}
{{- $gcp_service_account_name_sql := default .Values.infrastructure.configConnector.overrideCloudSQLGcloudSA (printf "%s@%s.iam.gserviceaccount.com" $gcp_service_account_name_sql_created .Values.infrastructure.gcp.projectId) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cloudsql
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
    "iam.gke.io/gcp-service-account": {{ $gcp_service_account_name_sql }}
---
