{{- /*
{{ .Release.Name }}-secrets resources. This Service Account is used for reading the secrets
from Secret Manager.
*/}}
---
{{- $gcp_service_account_name_created := include "celo.blockscout.sanitize-gcp-service-account-name" (dict "name" .Release.Name) -}}
{{- $gcp_service_account_name := .Values.infrastructure.configConnector.overrideCloudSecretsGcloudSA | default $gcp_service_account_name_created }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $gcp_service_account_name }}@{{ .Values.infrastructure.gcp.projectId }}.iam.gserviceaccount.com
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
