apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-api
  annotations:
    {{- include "celo.blockscout.annotations" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.blockscout.api.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.blockscout.api.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: blockscout
      release: {{ .Release.Name }}
      component: blockscout-api
  template:
    metadata:
      {{- if .Values.infrastructure.metrics.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "4000"
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app: blockscout
        release: {{ .Release.Name }}
        component: blockscout-api
        {{- include "celo.blockscout.elixir.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
        {{- include "celo.blockscout.initContainer.secrets-init" . | nindent 6 }}
      containers:
      {{- $data := dict "Release" .Release "Values" .Values "Database" .Values.blockscout.api.db -}}
      {{- include "celo.blockscout.container.db-sidecar" . | nindent 6 }}
      - name: blockscout-api
        image: {{ .Values.blockscout.shared.image.repository }}:api-{{ .Values.blockscout.shared.image.tag }}
        imagePullPolicy: {{ .Values.blockscout.shared.image.pullPolicy }}
        command:
        - /secrets/secrets-init
        args:
        - --provider
        - google
        - /bin/sh
        - -c
        - |
           exec mix cmd --app block_scout_web "iex --cookie $ERLANG_COOKIE  --name {{ .Values.blockscout.shared.erlangNodeName}}@$(POD_IP) -e 'IEx.configure(default_prompt: \"\", alive_prompt: \"\")' -S mix do deps.loadpaths --no-deps-check --no-validate-compile-env, phx.server --no-compile"
        volumeMounts:
        - mountPath: /secrets
          name: temporary-dir
          readOnly: true
        ports:
        - name: http
          containerPort: {{ .Values.blockscout.api.port }}
        {{- with .Values.blockscout.api.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.blockscout.api.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.blockscout.api.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: DISABLE_WEBAPP
          value: "true"
        - name: DISABLE_WRITE_API
          value: "true"
        - name: DISABLE_INDEXER
          value: "true"
        - name: DISABLE_EXCHANGE_RATES
          value: "true"
        - name: API_RATE_LIMIT
          value: {{ .Values.blockscout.api.rateLimit | quote }}
        - name: POOL_SIZE
          value: {{ .Values.blockscout.api.poolSize | quote }}
        - name: POOL_SIZE_API
          value: {{ .Values.blockscout.api.poolSizeReplica | quote }}
        - name: BLOCKSCOUT_HOST
          value: {{ .Values.blockscout.web.host | quote }}
        - name: ENABLE_SOURCIFY_INTEGRATION
          value: {{ .Values.blockscout.web.sourcify.enabled | quote }}
        - name: SOURCIFY_SERVER_URL
          value: {{ .Values.blockscout.web.sourcify.serverUrl | quote }}
        - name: SOURCIFY_REPO_URL
          value: {{ .Values.blockscout.web.sourcify.repoUrl | quote }}
        - name: CHAIN_ID
          value: {{ .Values.network.networkID | quote }}
        - name: MY_REGION
          value: {{ .Values.blockscout.api.rpcRegion | quote }}
        - name: FLY_REGION
          value: {{ .Values.blockscout.api.rpcRegion | quote }}
        - name: PRIMARY_REGION
          value: {{ .Values.blockscout.api.primaryRpcRegion | quote }}
        {{- if .Values.blockscout.api.suffix.enabled }}
        - name: NETWORK_PATH
          value: /{{ .Values.blockscout.api.suffix.path }}
        - name: API_PATH
          value: /{{ .Values.blockscout.api.suffix.path }}
        - name: API_URL
          value: /{{ .Values.blockscout.api.suffix.path }}
        - name: ACCOUNT_POOL_SIZE
          value: {{ .Values.blockscout.web.accountPoolSize | quote }}
        {{- end }}
        {{- include "celo.blockscout.env-vars" $data | nindent 8 }}
      volumes:
        {{- include "celo.blockscout.volume.cloudsql-credentials" . | nindent 8 }}
        {{- include "celo.blockscout.volume.temporary-dir" . | nindent 8 }}
      {{- $affinity := default .Values.infrastructure.affinity.affinity .Values.blockscout.api.affinity -}}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $nodeSelector := default .Values.infrastructure.affinity.nodeSelector .Values.blockscout.api.nodeSelector -}}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
