{{- $apiHostName := include "celo.blockscout.getHostName" (dict "Values" .Values "Release" .Release "component" "api") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-api-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /admin/.* {
        deny all;
      }
spec:
  ingressClassName: {{ default "nginx" .Values.ingressClassName }}
  tls:
  - hosts:
    - {{ $apiHostName }}
    secretName: {{ $apiHostName }}-tls
  rules:
  - host: {{ $apiHostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-api
            port: 
              number: 4000
