{{- if .Values.infrastructure.configConnector.cloudSQL.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudsql
  namespace: {{ .Values.infrastructure.configConnector.namespace }}
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
data:
  rootPassword: {{ .Values.infrastructure.configConnector.cloudSQL.rootPassword | b64enc | quote }}
  username: {{ .Values.infrastructure.configConnector.cloudSQL.username | b64enc | quote }}
  password: {{ .Values.infrastructure.configConnector.cloudSQL.userPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudsql
  namespace: {{ .Release.Namespace }}
data:
  rootPassword: {{ .Values.infrastructure.configConnector.cloudSQL.rootPassword | b64enc | quote }}
  username: {{ .Values.infrastructure.configConnector.cloudSQL.username | b64enc | quote }}
  password: {{ .Values.infrastructure.configConnector.cloudSQL.userPassword | b64enc | quote }}
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {{ include "celo.blockscout.instance-name" . }}
  namespace: {{ .Values.infrastructure.configConnector.namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: celo-testnet
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
spec:
  databaseVersion: POSTGRES_14
  region: {{ .Values.infrastructure.configConnector.cloudSQL.region }}
  rootPassword:
    value: "blockscout"
    # valueFrom:
    #   secretKeyRef:
    #     name: {{ .Release.Name }}-cloudsql
    #     key: rootPassword
  settings:
    tier: {{ .Values.infrastructure.configConnector.cloudSQL.tier }}
    diskSize: {{ .Values.infrastructure.configConnector.cloudSQL.diskSize }}
    diskType: {{ .Values.infrastructure.configConnector.cloudSQL.diskType }}
    diskAutoresize: {{ .Values.infrastructure.configConnector.cloudSQL.diskAutoresize }}
    availabilityType: ZONAL
    {{- if .Values.infrastructure.configConnector.cloudSQL.backupConfiguration.enabled }}
    backupConfiguration:
      enabled: true
      pointInTimeRecoveryEnabled: true
    {{- end }}
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  # name: {{ include "celo.blockscout.instance-name" . }}-{{ .Values.infrastructure.configConnector.cloudSQL.username }}
  name: "blockscout"
  namespace: {{ .Values.infrastructure.configConnector.namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: celo-testnet
spec:
  instanceRef:
    name: {{ include "celo.blockscout.instance-name" . }}
  password:
    value: "blockscout"
    # valueFrom:
    #   secretKeyRef:
    #     name: {{ .Release.Name }}-cloudsql
    #     key: password
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ include "celo.blockscout.instance-name" . }}
  namespace: {{ .Values.infrastructure.configConnector.namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: celo-testnet
spec:
  instanceRef:
    name: {{ include "celo.blockscout.instance-name" . }}
  charset: UTF8
  collation: en_US.UTF8
{{- end }}
