{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.environment }}-attestation-bot-secrets
  labels:
    app: attestation-bot
    chart: attestation-bot
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: attestation-bot
type: Opaque
data:
  mnemonic: {{ .Values.secrets.mnemonic | default "" | b64enc }}
  twilioAccountSid: {{ .Values.secrets.accountSid | default "" | b64enc }}
  twilioAuthToken: {{ .Values.secrets.authToken | default "" | b64enc }}
  twilioAddressSid: {{ .Values.secrets.addressSid | default "" | b64enc }}
{{- end }}
