apiVersion: v1
kind: Service
metadata:
  name: {{ include "eksportisto-monitoring.fullname" . }}
  labels:
  {{- include "eksportisto-monitoring.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: {{ include "eksportisto-monitoring.fullname" . }}-http-metrics
  selector:
  {{- include "eksportisto-monitoring.selectorLabels" . | nindent 4 }}
