apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eksportisto-monitoring.fullname" . }}
  labels:
    {{- include "eksportisto-monitoring.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eksportisto-monitoring.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "eksportisto-monitoring.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "eksportisto-monitoring.labels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -config.file=/etc/agent/agent.yaml
        - -enable-features=integrations-next
        - -server.http.address=0.0.0.0:80
        command:
        - /bin/agent
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ include "eksportisto-monitoring.fullname" . }}
        ports:
        - containerPort: 80
          name: http-metrics
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/agent
          name: agent-wal
        - mountPath: /etc/agent
          name: {{ include "eksportisto-monitoring.fullname" . }}
      serviceAccount: {{ include "eksportisto-monitoring.serviceAccountName" . }}
      volumes:
      - configMap:
          name: {{ include "eksportisto-monitoring.fullname" . }}
        name: {{ include "eksportisto-monitoring.fullname" . }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: agent-wal
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
