---
apiVersion: v2
appVersion: "1.6.0"
description: Helm chart for deploying a Celo fullnode.
  More info at https://docs.celo.org
type: application
home: https://celo.org
icon: >
  https://github.com/celo-org/charts/blob/main/static/celo_logo256x256.png?raw=true
name: celo-fullnode
sources:
  - https://celo.org
  - https://docs.celo.org
  - https://clabs.co
  - https://github.com/celo-org
keywords:
  - Celo
  - Blockchain
  - Fullnode
  - Validator
  - Ethereum
  - Proof-of-Stake
version: 0.4.8
dependencies:
  - name: common
    repository: oci://us-west1-docker.pkg.dev/devopsre/clabs-public-oci
    version: 0.2.6
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
