affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: pool
          operator: In
          values:
          - n2d-highcpu-8-spot

geth:  
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetAverageUtilization: 80
