---
apiVersion: v2
appVersion: "0.1.0"
description: Helm chart for deploying Celo Safe Client Gateway
type: application
home: https://celo.org
icon: >
  https://github.com/celo-org/charts/blob/main/static/celo_logo256x256.png?raw=true
name: safe-client-gateway
sources:
  - https://celo.org
  - https://safe.celo.org/#/welcome
  - https://clabs.co
  - https://github.com/celo-org/safe-client-gateway
  - https://gnosis-safe.io/
keywords:
  - Celo
  - Safe
  - Gateway
version: 1.1.3
dependencies:
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
