{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digester-system.fullname" . }}
  labels:
    {{- include "digester-system.labels" . | nindent 4 }}
rules:
- resources:
  - secrets # access to imagePullSecrets
  - serviceaccounts # access to imagepullSecrets
  apiGroups:
  - ''
  verbs:
  - get
  - list
  - watch
- resources:
  - customresourcedefinitions
  apiGroups:
  - apiextensions.k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - mutatingwebhookconfigurations
  apiGroups:
  - admissionregistration.k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - mutatingwebhookconfigurations
  apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - digester-mutating-webhook-configuration
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}