{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digester-system.fullname" . }}
  labels:
    {{- include "digester-system.labels" . | nindent 4 }}
roleRef:
  name: {{ include "digester-system.fullname" . }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: {{ include "digester-system.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
{{- end }}
