apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digester-system.fullname" . }}
  labels:
    {{- include "digester-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "digester-system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "digester-system.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "digester-system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - webhook
            - --cert-dir=/certs
            - --disable-cert-rotation=false
            - --dry-run=false
            - --health-addr=:9090
            - --metrics-addr=:8888
            - --offline=true
            - --port=8443
          ports:
            - name: webhook-server
              protocol: TCP
              containerPort: 8443
            - name: metrics
              protocol: TCP
              containerPort: 8888
            - name: healthz
              protocol: TCP
              containerPort: 9090
          livenessProbe:
            httpGet:
              port: healthz
              path: /healthz
          readinessProbe:
            httpGet:
              port: healthz
              path: /readyz
          volumeMounts:
            - name: cert
              readOnly: true
              mountPath: /certs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "digester-system.fullname" . }}
