apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "digester-system.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "digester-system.labels" . | nindent 4 }}
roleRef:
  name: {{ include "digester-system.fullname" . }}
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: {{ include "digester-system.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
