apiVersion: v1
kind: Service
metadata:
  name: {{ include "digester-system.svc-name" . }}
  labels:
    {{- include "digester-system.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook-server
      protocol: TCP
      name: http
  selector:
    {{- include "digester-system.selectorLabels" . | nindent 4 }}
