{{- with .Values.services.rpc }}
{{- if .sharedServiceEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-geth.fullname" $ }}-shared-rpc
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: rpc
    {{- include "op-geth.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  publishNotReadyAddresses: false
  ports:
    - name: http
      port: {{ .httpPort }}
      targetPort: http
    {{- if and $.Values.config.ws.enabled (and (ne .httpPort .wsPort) (ne .Values.config.http.port .Values.config.http.port)) }}
    - name: ws
      port: {{ .wsPort }}
      targetPort: ws
    {{- end }}
  selector:
    {{- include "op-geth.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
