apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-signer-service.fullname" . }}
  labels:
    {{- include "op-signer-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "op-signer-service.port" . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.tls.enabled}}
    - port: {{ include "op-signer-service.tls-port" . }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end}}
  selector:
    {{- include "op-signer-service.selectorLabels" . | nindent 4 }}
