# Default values for pr-url-checker-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Chart name override
nameOverride: ""
# -- Chart full name override
fullnameOverride: ""

# -- Number of deployment replicas
replicaCount: 1

image:
  # -- Image repository
  repository: us-west1-docker.pkg.dev/devopsre/pr-url-checker-app/pr-url-checker-app
  # -- Image pullpolicy
  pullPolicy: IfNotPresent
  # -- Image tag
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# -- Image pull secrets
imagePullSecrets: []

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
    # iam.gke.io/gcp-service-account: pr-url-checker-app-batcher@blockchaintestsglobaltestnet.iam.gserviceaccount.com
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Env Vars. for the pod.
env: {}
  # workflowFileName: "workload-id-tf.yaml"
  # organization: "celo-org"
  # repo: "infrastructure"

# -- Env Vars. coming form a secret.
secretEnv: {}
  # webhookSecret:
  #   secretName: "test"
  #   secretKey: "test"
  # githubToken:
  #   secretName: "test"
  #   secretKey: "test"

ingress:
  # -- Ingress enabled
  enabled: false
  # -- Ingress class name
  className: nginx
  # -- Custom Ingress annotations
  annotations: {}

  # -- List of hosts to expose safe-config-service. See values.yaml for an example.
  hosts: []
    # - host: pr-url-checker-app.akeyless.celo-networks-dev.org
    #   paths:
    #     - path: /

  # -- TLS secret for exposing safe-config-service with https. See values.yaml for an example.
  tls: []
    # - secretName: cpr-url-checker-app-tls
    #   hosts:
    #      - pr-url-checker-app.akeyless.celo-networks-dev.org

# -- Custom pod annotations
podAnnotations: {}
  # prometheus.io/path: /metrics
  # prometheus.io/port: "7300"
  # prometheus.io/scrape: "true"

# -- Custom pod labels
podLabels: {}

# -- Custom pod security context
podSecurityContext: {}
  # fsGroup: 2000

# -- Custom container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Container resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Liveness probe
livenessProbe: {}
  # httpGet:
  #   path: /hook
  #   port: http

# -- Readiness probe
readinessProbe: {}
  # httpGet:
  #   path: /hook
  #   port: http

# -- Kubernetes node selector
nodeSelector: {}

# -- Kubernetes tolerations
tolerations: []

# -- Kubernetes pod affinity
affinity: {}
