apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname" . }}-geth-account
  labels:
    {{- include "common.standard.labels" .  | nindent 4 }}
type: Opaque
data:
  accountSecret: {{ .Values.geth.account.secret | b64enc }}
  mnemonic: {{ .Values.mnemonic | b64enc }}
  {{- if .Values.bootnode.privateKey }}
  privateKey: {{ .Values.bootnode.privateKey | b64enc }}
  {{- end }}
