controller:
  image:
    repository: ghcr.io/zapier/prom-aggregation-gateway
    tag: latest
  apiPort: 8080
  lifecyclePort: 8888
  replicaCount: 1
  type: Deployment
  env:
    GIN_MODE: release
  tolerations: []
  nodeSelector: {}

podMonitor:
  create: false
  additionalLabels: {}

podAnnotations: {}

service:
  create: true
  annotations: {}
  type: ClusterIP
  port: 8080
  nodePort: ""

serviceMonitor:
  create: false
  additionalLabels: {}

ingress:
  # -- Enable ingress resource
  enabled: false
  # -- Ingress class name
  className: "nginx"
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress hostnames
  hosts: []
  #  - host: chart-example.local
  #    paths:
  #      - path: /
  #        pathType: ImplementationSpecific
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
