apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "cel2-migration-tool.labels" . | nindent 4 }}
    component: cel2-migration-tool
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            {{- include "cel2-migration-tool.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "cel2-migration-tool.serviceAccountName" . }}
          initContainers:
          - name: download-dependencies
            image: {{ .Values.downloadDeps.image.repository }}:{{ .Values.downloadDeps.image.tag }}
            imagePullPolicy: {{ .Values.downloadDeps.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            args:
            - |
              {{- include (print $.Template.BasePath "/scripts/_download-deps.tpl") . | nindent 14 }}
            volumeMounts:
            - mountPath: /output
              name: output
            {{- if not .Values.pvc.useOutputAsInput }}
            - mountPath: /input
              name: input
            {{- end }}
          - name: migration
            image: {{ .Values.migrationTool.image.repository }}:{{ .Values.migrationTool.image.tag }}
            imagePullPolicy: {{ .Values.migrationTool.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            args:
            - |
              {{- include (print $.Template.BasePath "/scripts/_migration.tpl") . | nindent 14 }}
            {{- with .Values.migrationTool.resources }}
            resources:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            volumeMounts:
            - mountPath: /output
              name: output
          containers:
          - name: compress-and-upload
            image: {{ .Values.compressAndUpload.image.repository }}:{{ .Values.compressAndUpload.image.tag }}
            imagePullPolicy: {{ .Values.compressAndUpload.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            args:
            - |
              {{- include (print $.Template.BasePath "/scripts/_compress-and-upload.tpl") . | nindent 14 }}
            volumeMounts:
            - mountPath: /output
              name: output
          volumes:
            {{- if not .Values.pvc.useOutputAsInput }}
            - name: input
              persistentVolumeClaim:
                claimName: {{ .Values.pvc.input }}
            {{- end }}
            - name: output
              persistentVolumeClaim:
                claimName: {{ .Values.pvc.output }}
          restartPolicy: Never
