---
releases:
  - name: baklava-blockscout3
    chart: oci://us-west1-docker.pkg.dev/devopsre/clabs-public-oci/blockscout
    version: ~1
    createNamespace: false
    namespace: baklava
    missingFileHandler: Error
    values:
      - ../../charts/blockscout/values-baklava-blockscout3.yaml
      - changeCause: {{ env "CHANGE_CAUSE" }}
