apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-node.fullname" . }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
data:
  jwt.hex: {{ .Values.config.jwt | b64enc | quote }}
  p2p.hex: {{ .Values.config.p2p.keys | b64enc | quote }}
  {{- if .Values.config.p2p.sequencer.key }}
  sequencer.hex: {{ .Values.config.p2p.sequencer.key | b64enc | quote }}
  {{- end }}
