apiVersion: v2
name: llama-web3-proxy
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "0.1.0"
home: https://celo.org
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
sources:
  - https://github.com/llamanodes/web3-proxy
keywords:
  - Ethereum
  - RPC
  - Proxy
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
dependencies:
  - name: redis
    version: 19.3.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
