---
replicaCount: 1

init:
  image:
    repository: alpine
    tag: 3.19
    pullPolicy: IfNotPresent
  rollup:
    url: https://storage.googleapis.com/cel2-rollup-files/dango/rollup.json

image:
  repository: us-west1-docker.pkg.dev/blockchaintestsglobaltestnet/dev-images/op-conductor
  tag: ea8d7ce5425edb3d1adcf0a8bb2a98fcdb21b3e0
  pullPolicy: IfNotPresent
statefulset:
  annotations: {}
  podAnnotations: {}

config:
  execution:
    # execution engine (op-geth) rpc endpoint
    rpc: http://op-geth:8545
  node:
    rpc: http://op-node:8547
  consensus:
    # Address to listen for consensus connections. It cannot be 0. If empty, it will try to use
    # the service ip or the pod ip.
    addr: ""
    port: 50050
  raft:
    bootstrap: false
    server:
      id: 1
    storage:
      dir: /raft
  rpc:
    enableAdmin: false
    enableProxy: true
    addr: 0.0.0.0
    port: 8545
  healthcheck:
    interval: 10
    minPeerCount: 1
    safeEnabled: false
    safeInterval: 1200
    unsafeInterval: 10000
  log:
    format: json
    level: INFO
  metrics:
    enabled: true
    addr: 0.0.0.0
    port: 7300
  network: ""
  paused: false
podSecurityContext: {}

persistence:
  type: pvc
  pvc:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: ""
    annotations:
      # resize.topolvm.io/increase: 1Gi
      # resize.topolvm.io/storage_limit: 5Gi
      # resize.topolvm.io/threshold: 10%
      # resize.topolvm.io/inodes-threshold: 5%
  mountPath: /raft

services:
  rpc:
    type: ClusterIP
    loadBalancerIPs: []
    clusterIPs: []
    port: 8545
    annotations: {}
    publishNotReadyAddresses: true
  consensus:
    type: ClusterIP
    loadBalancerIPs: []
    clusterIPs: []
    port: 50050
    annotations: {}
    publishNotReadyAddresses: true
