apiVersion: v2
name: team-trigger-workflow
description: A Helm chart to run team-trigger-workflow at cLabs
type: application
version: 0.1.4
appVersion: "latest"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
sources:
  - https://github.com/celo-org/team-trigger-workflow
