{{- if or .Values.secrets.privateKey.value .Values.secrets.l1Url.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-batcher.fullname" . }}
  labels:
    {{- include "op-batcher.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets.privateKey.value }}
  privateKey: {{ toString . | b64enc | quote }}
  {{- end }}
  {{- with .Values.secrets.l1Url.value }}
  l1Url: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
