{{- if .Values.secrets.jwt.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-conductor.fullname" . }}
  labels:
    {{- include "op-conductor.labels" . | nindent 4 }}
data:
  jwt: {{ .Values.secrets.jwt.value | b64enc | quote }}
{{- end }}
