---
replicaCount: 1
network: mainnet
networkId: 42220
affinity: {}
nodeSelector: {}
tolerations: {}
image:
  repository: us.gcr.io/celo-testnet/rosetta
  tag: gingerbread-prep-2
resources:
  requests:
    cpu: 7
    memory: 12Gi
storage:
  # -- Name of the storage class to use for the celo-blockchain statefulset
  storageClass: premium-rwo
  # -- accessMode for the volumes
  accessModes: ReadWriteOnce
  # -- celo-blockchain pvc annotations
  annotations:
    resize.topolvm.io/increase: 10%
    resize.topolvm.io/storage_limit: 3000Gi
    resize.topolvm.io/threshold: 85%
    resize.topolvm.io/inodes-threshold: 90%
  # -- Size of the persistent volume claim for the celo-blockchain statefulset
  size: 200Gi
  # -- Include a dataSource in the volumeClaimTemplates
  dataSource: {}
    # apiGroup: snapshot.storage.k8s.io
    # kind: VolumeSnapshot
    # name: forno-snapshot

cli:
  image:
    repository: us.gcr.io/celo-testnet/rosetta-cli
    tag: v0.10.3
