apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "clean-pvcs.fullname" . }}
  labels:
    {{- include "clean-pvcs.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - delete
