apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clean-pvcs.serviceAccountName" . }}
  labels:
    {{- include "clean-pvcs.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
