---
{{- if and (not .Values.env.db.passwordExistingSecret) (.Values.env.db.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odis-signer.secret-db-password" . }}
  labels:
    {{- include "odis-signer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "odis-signer.secret-db-password" . }}: {{ .Values.env.db.password | quote }}
{{- end }}
