---
{{- if and (not .Values.env.blockchain.blockchainApiKeyExistingSecret) (.Values.env.blockchain.blockchainApiKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odis-signer.secret-forno-key" . }}
  labels:
    {{- include "odis-signer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "odis-signer.secret-forno-key" . }}: {{ .Values.env.blockchain.blockchainApiKey | quote }}
{{- end }}
