apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-proxyd.fullname" . }}
  labels:
    {{- include "op-proxyd.labels" . | nindent 4 }}
data:
  config: |
    {{- tpl .Values.config . | nindent 4 }}