apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-proxyd.fullname" . }}
  labels:
    {{- include "op-proxyd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.rpcPort }}
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- end }}
    {{- if .Values.service.wsPort }}
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
    {{- end }}
  selector:
    {{- include "op-proxyd.selectorLabels" . | nindent 4 }}
