apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "op-tx-overload.fullname" . }}
  labels:
    {{- include "op-tx-overload.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "op-tx-overload.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "op-tx-overload.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.metrics.enabled }}
        prometheus.io/path: /metrics
        prometheus.io/port: "7300"
        prometheus.io/scrape: "true"
        {{- end }}
      labels:
        {{- include "op-tx-overload.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "op-tx-overload.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bin/sh
          - -c
          args:
          - |
            RID=$(echo $HOSTNAME | sed 's/{{ .Release.Name }}-//')
            STARTING_INDEX=$((RID * {{ .Values.config.numDistributors }}))
            /tx-overload.bin \
              --eth-rpc={{ .Values.config.ethRpc }} \
              --tx-mode={{ .Values.config.txMode }} \
              --num-distributors={{ .Values.config.numDistributors }} \
              --starting-index=$STARTING_INDEX \
              --data-rate={{ .Values.config.dataRate }} \
              --log.format={{ .Values.config.logFormat }} \
              {{- if .Values.metrics.enabled }}
              --metrics.enabled \
              {{- end }}
              {{- with .Values.extraArgs }}
              {{- toYaml . | nindent 14 }} \
              {{- end }}

          {{- if .Values.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: 7300
              protocol: TCP
          {{- end }}
          {{- if .Values.secretEnv }}
          env:
          {{- with .Values.secretEnv }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
            {{- end }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates: []
  updateStrategy:
    type: RollingUpdate
