---
{{- if and (.Values.env.privateKey) (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odis-loadtest.secret" . }}
  labels:
    {{- include "odis-loadtest.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "odis-loadtest.secret" . }}: {{ .Values.env.privateKey }}
{{- end }}
