---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    component: load-test
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    component: load-test
