{{- if .Values.geth.staticNodes }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.fullname" . }}-config
  labels:
    app: load-test
    chart: load-test
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: load-test
data:
  static-nodes.json: {{ .Values.geth.staticNodes | b64dec | quote }}
{{- end }}
