{{- if (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    app: load-test
    chart: load-test
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: load-test
type: Opaque
data:
  accountSecret: {{ .Values.secrets.accountSecret | b64enc }}
  mnemonic: {{ .Values.secrets.mnemonic | b64enc }}
{{- end }}
