apiVersion: v2
name: op-signer-service
description: A Helm chart for OP signer service
type: application
version: 0.1.0
appVersion: "v0.0.2"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
