apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.geth.persistence.size | quote }}
  storageClassName: {{ .Values.geth.persistence.storageClassName }}
  volumeMode: Filesystem
  {{- if .Values.geth.initial_snapshot.enabled }}
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: {{ .Values.geth.initial_snapshot.kind | default "VolumeSnapshot" }}
    name: {{ template "common.fullname" . }}-initial
  {{- end }}
