{{- if not (or (.Values.global.JWTSecret.value) (.Values.global.JWTSecret.secretName)) }}
{{- fail ".Values.global.JWTSecret.value or .Values.global.JWTSecret.secretName is required" }}
{{- end }}

{{- $endpoints := uniq .Values.global.executionEndpoints -}}
{{- if lt (len $endpoints) (len .Values.global.executionEndpoints)}}
{{- fail ".Values.global.executionClients must only contain unique values, since each consensus client must be connected to a unique execution client." }}
{{- end }}
