{{- if .Values.deletePodCronJob.enabled -}}
{{- /*
This CronJob in intended to delete regularly a geth pod
in order to force geth to flush the data to disk, so it can 
be used as an snapshot
*/}}
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "common.standard.labels" . | nindent 4 }}
    component: restart-geth
  name: {{ template "common.fullname" . }}-restart-geth
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "common.standard.labels" . | nindent 12 }}
            component: restart-geth
        spec:
          containers:
          - name: restart-geth
            command:
            - /bin/bash
            - -c
            args:
            - |
              # Delete the pod to force geth to flush the data to disk
              extraFlagsPod="{{ .Values.deletePodCronJob.extraFlagsPod }}"
              kubectl delete pod -n {{ .Release.Namespace }} {{ printf "%s-%d" (include "common.fullname" .) (.Values.deletePodCronJob.podIndex | int) }} $extraFlagsPod

              # Delete pvc that are not currently used
              extraFlagsPvc="{{ .Values.deletePodCronJob.extraFlagsPvc }}"
              unused_pvcs="$(kubectl describe pvc | grep -E "^Name:.*$|^Namespace:.*$|^Used By:.*$" | grep -B 2 "<none>" | grep -E "^Name:.*$")"
              while IFS= read -r line; do
                pvc=$(echo $line | awk '{print $2}')
                echo "Deleting pvc $pvc"
                kubectl delete pvc -n {{ .Release.Namespace }} $pvc $extraFlagsPvc
              done <<< "$unused_pvcs"
            image: bitnami/kubectl:latest
            imagePullPolicy: Always
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          serviceAccountName: {{ template "common.fullname" . }}-restart-geth
          terminationGracePeriodSeconds: 30
  schedule: "{{ .Values.deletePodCronJob.schedule }}"
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "common.standard.labels" . | nindent 4 }}
    component: restart-geth
  name: {{ template "common.fullname" . }}-restart-geth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "common.standard.labels" . | nindent 4 }}
    component: restart-geth
  name: {{ template "common.fullname" . }}-restart-geth
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "common.standard.labels" . | nindent 4 }}
    component: restart-geth
  name: {{ template "common.fullname" . }}-restart-geth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.fullname" . }}-restart-geth
subjects:
- kind: ServiceAccount
  name: {{ template "common.fullname" . }}-restart-geth
  namespace: {{ .Release.Namespace }}
{{- end }}
