apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.svcHeadless }}
  clusterIP: None
{{- end }}
{{- if .Values.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.sessionAffinity.timeoutSeconds }}
{{- end }}
  ports:
  {{- if .Values.jsonrpc.enabled }}
    - port: {{ .Values.jsonrpc.ports.rest }}
      targetPort: json-rest
      protocol: TCP
      name: json-rest
    - port: {{ .Values.jsonrpc.ports.websocket }}
      targetPort: json-ws
      protocol: TCP
      name: json-ws
  {{- end }}
  {{- if or (.Values.global.JWTSecret.value) (.Values.global.JWTSecret.secretName) }}
    - port: {{ .Values.jsonrpc.engine.port }}
      targetPort: engine
      protocol: TCP
      name: engine
  {{- end }}
  {{- if .Values.global.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}

{{- range $i, $e := until (int .Values.global.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}-{{ $i }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    pod: "{{ include "common.names.fullname" $ }}-{{ $i }}"
spec:
  type: {{ $.Values.service.type }}
{{- if $.Values.svcHeadless }}
  clusterIP: None
{{- end }}
{{- if $.Values.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ $.Values.sessionAffinity.timeoutSeconds }}
{{- end }}
  ports:
  {{- if $.Values.jsonrpc.enabled }}
    - port: {{ $.Values.jsonrpc.ports.rest }}
      targetPort: json-rest
      protocol: TCP
      name: json-rest
    - port: {{ $.Values.jsonrpc.ports.websocket }}
      targetPort: json-ws
      protocol: TCP
      name: json-ws
  {{- end }}
  {{- if $.Values.global.JWTSecret }}
    - port: {{ $.Values.jsonrpc.engine.port }}
      targetPort: engine
      protocol: TCP
      name: engine
  {{- end }}
  {{- if $.Values.global.metrics.enabled }}
    - port: {{ $.Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "common.names.fullname" $ }}-{{ $i }}"

{{- end }}
