---
name: faucet-distribution-cronjob
apiVersion: v2
version: 0.1.4
description: Calls CeloDistributionSchedule to distribute funds to the faucet
home: https://clabs.co
sources:
  - https://celo.org
  - https://docs.celo.org
  - https://clabs.co
  - https://github.com/celo-org
keywords:
  - celo
  - blockchain
  - faucet
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
type: application
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
appVersion: v1.0.0
