apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts-exporter.fullname" . }}
  labels:
    {{- include "accounts-exporter.labels" . | nindent 4 }}
data:
  addressess: |
    {{- tpl .Values.addressess . | nindent 4 }}