---
{{- if and (.Values.env.blockchain.blockchainApiKey) (not .Values.env.blockchain.blockchainApiKeyExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odis-combiner.secret" . }}
  labels:
    {{- include "odis-combiner.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "odis-combiner.secret" . }}: {{ .Values.env.blockchain.blockchainApiKey }}
{{- end }}
