apiVersion: v1
kind: Service
metadata:
  name: {{ include "odis-combiner.fullname" . }}
  labels:
    {{- include "odis-combiner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "odis-combiner.port" . }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odis-combiner.selectorLabels" . | nindent 4 }}
