---
apiVersion: v2
name: clean-pvcs
description: Delete PVCs not mounted for some time
type: application
version: 0.3.0
appVersion: "1.16.0"
home: https://celo.org
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
sources:
  - https://github.com/celo-org/charts/blob/main/charts/clean-pvcs/templates/cronjob.yaml
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
