---
name: celostats
apiVersion: v2
version: 0.1.1
description: Chart which is used to deploy a celostats setup for a celo testnet
home: https://clabs.co
sources:
  - https://celo.org
  - https://docs.celo.org
  - https://clabs.co
  - https://github.com/celo-org
keywords:
  - Celo
  - Ethereum
  - Blockchain
  - Celostats
  - Ethstats
appVersion: "latest"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
type: application
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
