apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-conductor-mon.fullname" . }}
  labels:
    {{- include "op-conductor-mon.labels" . | nindent 4 }}
data:
  config: |
    {{- tpl .Values.config . | nindent 4 }}