---
apiVersion: v2
name: op-conductor-mon
description: A Helm chart for OP Conductor monitoring
type: application
version: 0.1.1
appVersion: "main"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
sources:
  - https://github.com/celo-org/op-signer-service
