---
{{- if .Values.akeyless.gwApiUrl }}
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: akeyless-secret-store
spec:
  provider:
    akeyless:
      akeylessGWApiURL: {{ .Values.akeyless.gwApiUrl }}
      authSecretRef:
        secretRef:
          accessID:
            key: accessID
            name: akeyless-secret-store-secretref
            namespace: external-secrets
          accessType: 
            key: accessType
            name: akeyless-secret-store-secretref
            namespace: external-secrets
---
apiVersion: v1
stringData:
  accessID: {{ .Values.akeyless.authSecretRef.kubernetesAuth.accessID }}
  accessType: {{ .Values.akeyless.authSecretRef.kubernetesAuth.k8sConfName }}
kind: Secret
metadata:
  name: akeyless-secret-store-secretref
  namespace: external-secrets
type: Opaque
{{- end }}
