---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: "0s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        address: "{{`{{ .account.address }}`}}"
        signer: "{{`{{ .account.signer }}`}}"
  data:
    - secretKey: account
      remoteRef:
        key: /static-secrets/optics/mainnet/keymaster-optics-v1
