{{- $replicas := ternary .Values.geth.autoscaling.maxReplicas .Values.replicaCount .Values.geth.autoscaling.enabled }}
{{ range $index, $e := until (int $replicas ) }}
{{ range $protocolIndex, $protocol := $.Values.geth.service_protocols }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" $ }}-{{ $index }}-{{ lower $protocol }}
  {{- if $.Values.azure }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
  {{- end }}
  labels:
    {{- include "common.standard.labels" $ | nindent 4 }}
    component: celo-lightestnode-protocol-traffic
spec:
  type: {{ $.Values.geth.service_type }}
  publishNotReadyAddresses: true
  {{- if (and (eq $.Values.geth.service_type "LoadBalancer") (gt (len $.Values.geth.public_ip_per_node) $index)) }}
  loadBalancerIP: {{ index $.Values.geth.public_ip_per_node $index -}}
  {{- end }}
  ports:
    {{- if $.Values.geth.service_node_port_per_full_node }}
    {{- $port := index $.Values.geth.service_node_port_per_full_node $index }}
    - targetPort: {{ $port }}
      port: {{ $port }}
      nodePort: {{ $port }}
      name: tcp
      protocol: TCP
    - targetPort: {{ $port }}
      port: {{ $port }}
      nodePort: {{ $port }}
      name: udp
      protocol: UDP
    {{- else }}
    - port: 30303
      targetPort: 30303
      name: ethereum
      protocol: {{ $protocol }}
    {{- end }}
    {{- if $.Values.geth.expose_rpc_externally }}
    {{- include "celo-lightestnode.rpc-ports" . | nindent 4 }}
    {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "common.fullname" $ }}-{{ $index }}
{{- end }}
{{- end }}
