---
# Default values for ethereum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: Always

# Node labels for pod assignment
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# Insecure mnemonic
mnemonic: girl beauty clarify deliver force dynamic wonder shoe install erosion rib
  resource cannon topple prevent slot brown zero banana exercise quiz spot mercy misery

bootnode:
  image:
    repository: us.gcr.io/celo-testnet/geth-all
    tag: 21d8283af60927589566cb282ab640f1ccec6ebd
  bootnodeIpAddress: ""
  defaultBootnodeClusterIP: 10.0.0.12

celotool:
  image:
    repository: us.gcr.io/celo-testnet/celo-monorepo
    tag: celotool-dc5e5dfa07231a4ff4664816a95eae606293eae9

genesis:
  networkId: 1110
  network: testnet
  useGenesisFileBase64: false
  genesisFileBase64: ""
  # -- Genesis force URL
  genesisForceUrl: https://gist.githubusercontent.com/jcortejoso/eba86918c7b7c7546589edd9a32f1f08/raw/b564a1cb50c1fb5261ea5238b0c0b2d055af9ba4/genesis.json

geth:
  image:
    repository: us.gcr.io/celo-org/geth
    tag: 1.7.4
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits: {}
    # limits:
    #   memory: "4Gi"
    #   cpu: "4"
  storage: true
  diskSizeGB: 5
  privateTxNodediskSizeGB: 10
  ws_port: 8546
  account:
    secret: password
  static_ips: false
  txNodesIPAddressArray:
    - 1.2.3.4
  validatorExtraSnippet: |
    echo "Validator"
  secondayExtraSnippet: |
    echo "secondary-validator"
  proxyExtraSnippet: |
    echo "Proxy"
  txNodeExtraSnippet: |
    echo "txnode"
  txNodePrivateExtraSnippet: |
    echo "txnode-private"
    ADDITIONAL_FLAGS="${ADDITIONAL_FLAGS} --http.timeout.read 600 --http.timeout.write 600 --http.timeout.idle 2400"
  validatorNodeSelector: {}
  validatorTolerations: []
  secondaryNodeSelector: {}
  secondaryTolerations: []
  proxyNodeSelector: {}
  proxyTolerations: []
  txNodeNodeSelector: {}
  txNodeTolerations: []
  txNodePrivateNodeSelector: {}
  txNodePrivateTolerations: []
  ping_ip_from_packet: false
  faultyValidators: 0
  maxpeers: 1150
  light:
    maxpeers: 1000
    serve: 70
  verbosity: 1
  vmodule: consensus/*=2
  pprof:
    enabled: false
    port: 6060
metrics:
  enabled: true

replicas:
  validators: 3
  proxiesPerValidator:
    - 0
    - 1
    - 0
  secondaries: 0
  txNodes: 1
  txNodesPrivate: 1

# UpdateStrategy for statefulsets only. Partition=0 is default rollingUpdate behaviour.
updateStrategy:
  validators:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  secondaries:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  proxy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  tx_nodes:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  tx_nodes_private:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

blockscout:
  image:
    repository: gcr.io/celo-testnet/blockscout
    webTag: web
    indexerTag: indexer
  db:
    # ip: must be provided at runtime # IP address of the postgres DB
    # connection_name: must be provided at runtime # name of the cloud sql connection
    # username: blockscout
    # password: password
    name: blockscout

domain:
  name: celo-networks-dev

ingressClassName: nginx

extraPodLabels:
  validator:
    mode: full
  secondary:
    mode: full
  proxy:
    mode: full
  txnode:
    mode: full
  txnode_private:
    stack: blockscout
    mode: archive

pvcAnnotations:
  validator: {}
  secondary: {}
  proxy: {}
  txnode: {}
  txnode_private: {}

replicaInitialCount: 0
enableBootnode: true
enableFornoIngress: true
forceFornoDomain: ""
