apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-batcher.fullname" . }}
  labels:
    {{- include "op-batcher.labels" . | nindent 4 }}
data:
  privateKey: {{ .Values.config.privateKey | b64enc | quote }}