{{- with .Values.services.rpc }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-batcher.fullname" $ }}-rpc
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: rpc
    {{- include "op-batcher.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: rpc
      port: {{ .port }}
      targetPort: rpc
  selector:
    {{- include "op-batcher.selectorLabels" $ | nindent 4 }}
    {{- with $.Values.podStatusLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
