name: Helm Charts tests and docs

on:
  pull_request:
    branches:
      - main
    paths:
      # Run if any of the following files are changed
      - 'charts/**/templates/**'
      - 'charts/**/values.yaml'
      - 'charts/**/Chart.yaml'
      - 'charts/**/README.md.gotmpl'

jobs:

  helm-lint:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      HELM_VERSION: "v3.10.1"

    steps:
      - name: "Checkout current PR"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Install Helm"
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            changed=$(echo $changed | tr '\n' ' ')
            echo "changed_charts=$changed" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing if charts changed
        if: steps.list-changed.outputs.changed == 'true'
        uses: ./.github/workflows/chart_testing_action.yml
        with:
          changed-charts: ${{ steps.list-changed.outputs.changed_charts }}

  helm-docs:
    needs: helm-lint

    runs-on: 'ubuntu-latest'

    env:
      HELM_DOCS_VERSION: "1.11.0"

    permissions:
      contents: 'write'

    steps:
      - name: 'Checkout current PR'
        uses: actions/checkout@v2

      - name: 'install helm-docs'
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin

      - name: 'Run helm-docs in chaged charts'
        run: |
          helm-docs

      - name: "Commit updated README.md to the branch if changed"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Automatic] - Update chart README.md'
          file_pattern: 'charts/**/README.md'
