name: Helm Charts Auto-docs

on:
  pull_request:
    branches:
      - main
    paths:
      # Run if any of the following files are changed
      - 'charts/**/templates/**'
      - 'charts/**/values.yaml'
      - 'charts/**/Chart.yaml'
      - 'charts/**/README.md.gotmpl'

permissions:
  contents: write

env:
  HELM_DOCS_VERSION: "1.11.0"

jobs:
  helm-docs:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout current PR'
        uses: actions/checkout@v2

      - name: 'install helm-docs'
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin

      - name: 'Run helm-docs in chaged charts'
        run: |
          helm-docs 

      - name: "Commit updated README.md to the branch if changed"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Automatic] - Update chart README.md'
          file_pattern: 'charts/**/README.md'
