{{- if .Values.secrets.nodeKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-geth-bootnode.fullname" . }}
  labels:
    {{- include "op-geth-bootnode.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets.nodeKey.value }}
  nodeKey: {{ toString . | b64enc | quote }}
  {{- end }}
{{- end }}
