{{- with $.Values.services.p2p }}
{{- if and .enabled (not $.Values.config.useHostPort) }}
{{- $loadBalancerIP := "" }}
{{- $clusterIP := "" }}
{{- if .loadBalancerIP }}
  {{- $loadBalancerIP = .loadBalancerIP }}
{{- end }}
{{- if .clusterIP }}
  {{- $clusterIP = .clusterIP }}
{{- end }}
{{- if eq .type "LoadBalancer" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-geth-bootnode.fullname" $ }}-p2p-tcp
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: p2p
    {{- include "op-geth-bootnode.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with $loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: p2p-tcp
      port: {{ .port }}
      targetPort: p2p-tcp
      protocol: TCP
  selector:
    {{- include "op-geth-bootnode.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ template "op-geth-bootnode.fullname" $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-geth-bootnode.fullname" $ }}-p2p-udp
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: p2p
    {{- include "op-geth-bootnode.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with $loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: p2p-udp
      port: {{ .port }}
      targetPort: p2p-udp
      protocol: UDP
  selector:
    {{- include "op-geth-bootnode.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ template "op-geth-bootnode.fullname" $ }}
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-geth-bootnode.fullname" $ }}-p2p
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: p2p
    {{- include "op-geth-bootnode.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with $loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: p2p-tcp
      port: {{ .port }}
      targetPort: p2p-tcp
      protocol: TCP
    - name: p2p-udp
      port: {{ .port }}
      targetPort: p2p-udp
      protocol: UDP
  selector:
    {{- include "op-geth-bootnode.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ template "op-geth-bootnode.fullname" $ }}
{{- end }}
{{- end }}
{{- end }}
